baseURL = "/"
title = "Kagami Theme"
author = "Mayo"
paginate = 999
languageCode = "zh-Hans"
DefaultContentLanguage = "en"

[params]
mainSections = ["posts"]
description = 'Text about my cool site'
title = 'My cool site'

[params.social]
github = "https://github.com"
twitter = "https://twitter.com"

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1

[taxonomies]
tag = "tags"
series = "series"

[markup.highlight]
codeFences = false