baseURL = "/"
title = "Kagami Theme"
author = "Mayo"
paginate = 3
languageCode = "zh-Hans"
DefaultContentLanguage = "en"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1

[params.social]
github = "https://github.com"
twitter = "https://twitter.com"

[taxonomies]
tag = "tags"