baseURL = "/"
title = "Kagami Theme"
author = "Mayo"
paginate = 3
languageCode = "zh-Hans"
DefaultContentLanguage = "en"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
tag = "tags"