name = "Kagami"
license = "MIT"
licenselink = "https://github.com/mayocream/hugo-theme-kagami/LICENSE"
description = "Kagami theme for hugo"
homepage = "https://github.com/mayocream/hugo-theme-kagami"
tags = ["blog", "code", "simple"]
features = ["blog", "code", "simple"]
min_version = "0.60.1"

[author]
  name = "Mayo"
  homepage = "https://github.com/mayocream"

# If porting an existing theme
[original]
    author = "kamikat"
    homepage = "https://banana.moe"
    repo = "https://github.com/kamikat/jekyll-theme-kagami"